[options]
; This is the password that allows database operations:
admin_passwd = MonDongo4#
db_host = False
db_port = False
db_user = odoo14
db_password = False
addons_path = /opt/odoo14/odoo/addons,/opt/odoo14/odoo-custom-addons

;proxy_mode = True

;limit_memory_hard = 2147483648
;limit_memory_soft = 1020054732
;limit_request = 8192
;limit_time_cpu = 600
;limit_time_real = 1200
;max_cron_threads = 1
;workers = 2

; Filtrar bases de datos por el comienzo de la url y quitar la lista de bases de datos
;dbfilter = ^%h$
;list_db = False